In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import metrics
from sklearn.svm import SVC,SVR,LinearSVC

In [3]:
data=pd.read_csv('new_dataset2.csv')
data=data.drop(data.columns[[0,2,3,4,6]],axis=1)
data.head()

Favorite food names Food flavor
0                                                NaN       Sweet
1  Pasta, Pizza, Kacchi, Chinese, Traditional, Ri...       Spicy
2                                             Burger       Sweet
3                                    Kacchi Biriyani       Spicy
4                                              Kacci       Sweet

In [4]:
data.dropna(inplace=True)
data.head()

Favorite food names Food flavor
1  Pasta, Pizza, Kacchi, Chinese, Traditional, Ri...       Spicy
2                                             Burger       Sweet
3                                    Kacchi Biriyani       Spicy
4                                              Kacci       Sweet
5       Chinese, Pizza, Pasta, Noodles, Polao, Roast       Sweet

In [5]:
data.rename(columns={'Favorite food names': 'Food',
                    'Food flavor': 'Flavor'}, inplace = True)
data.head()

Food Flavor
1  Pasta, Pizza, Kacchi, Chinese, Traditional, Ri...  Spicy
2                                             Burger  Sweet
3                                    Kacchi Biriyani  Spicy
4                                              Kacci  Sweet
5       Chinese, Pizza, Pasta, Noodles, Polao, Roast  Sweet

In [6]:
data['Food'] = data['Food'].str.split(',').str[0]
data.head()

Food Flavor
1            Pasta  Spicy
2           Burger  Sweet
3  Kacchi Biriyani  Spicy
4            Kacci  Sweet
5          Chinese  Sweet

In [7]:
data['Food'] = data['Food'].str.lower()
data['Food'].unique()

array(['pasta', 'burger', 'kacchi biriyani', 'kacci', 'chinese', 'pizza',
       'icecream', 'kacchi', 'soup and onthon', 'grilled chicken',
       'not anything in particular', 'biriyani', 'fuchka', 'kachchi',
       'chicken fry', 'anything that tastes good', 'french fries',
       'coffee', 'milk', 'beef curry', 'hilsha', 'tehari', 'chicken',
       'kachchi biriyani', 'mutton biriyani', 'fish', 'pasta/pizza',
       'fried rice', 'nun-grill', 'shawrma', 'briyani', 'italian',
       'grill-nun', 'kacchi ', 'beef', 'cheescake', 'biriani', 'soup',
       'payes', 'waffle', 'elish'], dtype=object)

In [8]:
data.to_csv('processedFood.csv', index = False)

In [18]:
df = pd.read_csv('processedFood.csv')
df.head()

Food Flavor
0     pasta  Spicy
1    burger  Sweet
2  biriyani  Spicy
3  biriyani  Sweet
4   chinese  Sweet

In [19]:
df['Food'].unique()

array(['pasta', 'burger', 'biriyani', 'chinese', 'pizza', 'icecream',
       'soup', 'grilled chicken', 'none', 'fuchka', 'french fries',
       'coffee', 'milk', 'beef', 'fish', 'chicken', 'shawrma', 'italian',
       'cheesecake', 'payes', 'waffle'], dtype=object)

In [20]:
df['Flavor'].replace({
    'Spicy': 0,
    'Sweet': 1
}, inplace = True)
df.head()

Food  Flavor
0     pasta       0
1    burger       1
2  biriyani       0
3  biriyani       1
4   chinese       1

In [12]:
#food_list = df['Food'].unique().tolist()
#food_list

In [13]:
#vec = CountVectorizer()
#X = vec.fit_transform(food_list).toarray()

In [14]:
#y = df['Flavor'].values
#X = X.reshape(X.shape[1:])
#xTrain, yTrain, xTest, yTest = train_test_split(X, y, test_size=0.25, random_state = 0)

In [15]:
#print(X.shape)
#y.shape

In [21]:
df['Food'].replace({
    'none': 0,
    'pasta': 1,
    'burger':2,
    'biriyani':3,
    'chinese': 4,
    'pizza': 5,
    'icecream': 6,
    'soup': 7,
    'grilled chicken': 8,
    'fuchka': 9,
    'french fries': 10,
    'coffee': 11,
    'milk': 12,
    'beef': 13,
    'fish' : 14,
    'chicken': 15,
    'shawrma': 16,
    'italian': 17,
    'cheesecake': 18,
    'payes': 19,
    'waffle': 20
}, inplace = True)

In [22]:
df.head()

Food  Flavor
0     1       0
1     2       1
2     3       0
3     3       1
4     4       1

In [23]:
D = df.values
X = D[:,:-1]
y = D[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.25)

In [24]:
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, Y_train)
yPred=clf.predict(X_test.astype(int))
acc=accuracy_score(Y_test.astype(int), yPred.astype(int))
print('Accuracy with 3 neighbours: ',acc)
confusion_matrix(Y_test, yPred)

Accuracy with 3 neighbours:  0.5769230769230769


array([[15,  0],
       [11,  0]], dtype=int64)

In [25]:
clfNB = BernoulliNB()
clfNB.fit(X_train, Y_train)
yPredNB=clfNB.predict(X_test
accNB=accuracy_score(Y_test.astype(int), yPredNB.astype(int))
print(accNB)
confusion_matrix(Y_test, yPredNB)

0.5769230769230769


array([[15,  0],
       [11,  0]], dtype=int64)

In [26]:
clfSVM = LinearSVC(random_state=0, tol=1e-5)
clfSVM.fit(X_train, Y_train)
yPredSVM = clfSVM.predict(X_test)
accSVM=accuracy_score(Y_test, yPredSVM)
print(accSVM)
confusion_matrix(Y_test, yPredSVM)

0.5769230769230769


c:\users\farzana\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([[15,  0],
       [11,  0]], dtype=int64)

In [27]:
df.corr()

Food    Flavor
Food    1.000000  0.158632
Flavor  0.158632  1.000000